#ifndef SERVER_H_INCLUDED
#define SERVER_H_INCLUDED

#define TRUE 1
#define FALSE 0

#define MAX_CLIENTS 10
#define BUFFER_SIZE 1024
#define FORMATTING_BUFFER_SIZE 1024
#define PATH_SIZE 512
#define USERNAME_SIZE 16

#endif